### ISSUE TITLE
Wrong extraProperties returned when calling /users route

### ISSUE THREAD

**Issue by rbott** [FactoryCampus/radau#1]
When I directly query users I receive their correct `extraProperties` (e.g. via /radius/someUser).

When I call the `/users` route (which should dump all users and their extra-properties) I receive the same set of `extraProperties` for each user.

This is the (shortened) reply from the server.
```
{
   "users" : [
      {
         "lastQuery" : "2018-06-18T16:12:48.128917Z",
         "extraProperties" : {
            "Tunnel-Private-Group-Id" : "100"
         },
         "token" : "1234567",
         "username" : "user1@domain.de"
      },
      {
         "token" : "1234567",
         "username" : "user2@domain.de",
         "lastQuery" : "2018-06-18T16:12:30.128917Z",
         "extraProperties" : {
            "Tunnel-Private-Group-Id" : "100"
         }
      },
      {
         "extraProperties" : {
            "Tunnel-Private-Group-Id" : "100"
         },
         "lastQuery" : "2018-06-18T16:10:00.128917Z",
         "username" : "user3@domain.de",
         "token" : "1234567"
      }

      [...]
      
   ],
   "userCount" : 40
}
```

This is the example Script used to generate the above output:
```
#!/usr/bin/python

import requests

host = "http://radau.domain:8080"
url = "/users"
headers = { "Authorization": "aAbBcCdDeEfFgGhH"}

try:
    r = requests.get(host + url, headers=headers)
    if r.status_code == 200:
        print(r.text)
    else:
        print("Unexpected Return Code: {0}".format(r.status_code))
except Exception as err:
    print("Connection error: {0}".format(err))
```

Directly retrieving user1, user2, user3 whould show that they actually have different extraProperties configured. In this case all of them have only configured `Tunnel-Private-Group-Id` with different values.

If I update the `extraProperties` of any given user, the next call to `/users` will contain exactly this set of `extraProperties` set for _all_ users.

**Comment by mraerino** [comment]
This has been fixed in [Release 1.1.1](../releases/tag/1.1.1) 🎉
