### ISSUE TITLE
Readme.md Fix

### ISSUE THREAD

**Issue by fbrandt-dev** [FactoryCampus/radau#2]
Missing requirements before:
 **docker network create wifi_db**

docker run -d --name wifilogin \
    -e API_KEY_MANAGEMENT= -e API_KEY_RADIUS= \
    -e DB_HOST=wifilogin_db -e DB_USER=wifi -e DB_PASSWORD=wifi -e DB_DATABASE=wifi \
    -p 8080:8080 --network wifi_db **\\**  <-- Missing Backspace
    factorycampus/**radau** <-- Repo and Docker-Hub have been renamed

**Comment by mraerino** [comment]
Hi 👋 Thanks for the issue!

Would you like to be the author of the commit that fixes this?
If so, please submit a pull request. ✨

**Comment by mraerino** [comment]
Fixed in #3
